// ============================================================
// 📦 Question Data Model
// ============================================================

import { ClassType } from './CharacterClass';
import { QuestionDifficulty } from './Skill';

export interface QuestionData {
  id?: number;           // Auto-generated by Dexie
  prompt: string;        // Thai question text
  choices: string[];     // 4 choices (Thai)
  correctIndex: number;  // Index of correct choice (0-3)
  category: ClassType;   // Which character class this question belongs to
  difficulty: number;    // 1-5 (1=ง่ายมาก, 5=ยากมาก)
  assignedSkillId: string; // Which skill this question is for (or '' for generic)
  usesRemaining: number; // Max 3 — decremented each time used
}

/** Create a new question with default values */
export function createQuestion(
  prompt: string,
  choices: string[],
  correctIndex: number,
  category: ClassType,
  difficulty: number,
  assignedSkillId: string = '',
): QuestionData {
  return {
    prompt,
    choices,
    correctIndex,
    category,
    difficulty,
    assignedSkillId,
    usesRemaining: 3, // Default: 3 uses
  };
}

/** Map numeric difficulty (1-5) to QuestionDifficulty enum */
export function numericToQuestionDifficulty(value: number): QuestionDifficulty {
  if (value <= 2) return QuestionDifficulty.Easy;
  if (value <= 3) return QuestionDifficulty.Medium;
  return QuestionDifficulty.Hard;
}

/** Map QuestionDifficulty to required numeric range */
export function questionDifficultyToNumeric(diff: QuestionDifficulty): [number, number] {
  switch (diff) {
    case QuestionDifficulty.Easy: return [1, 2];
    case QuestionDifficulty.Medium: return [3, 3];
    case QuestionDifficulty.Hard: return [4, 5];
  }
}
